os:
- Mac OS X
#- Windows Server 2012 R2

environment:
  myvar1: Hello, world!
  ANOTHER_VAR: Test!!!

install:
- echo "THIS IS PRIVATE PROJECT!"
- sh: sw_vers
- echo "Should be run on both Windows and Mac"
- sh: ENV
- batch: should be skipped by both platforms
- ps: 'gci env:'
- ls
- sh: ls $HOME
- sh: echo "This is Bash script!"
- npm --version
- ps: 'Write-Host "This is run on Windows only: $env:USERPROFILE"'
- cmd: 'echo This run on Windows too: %USERPROFILE%'

build: off

test: off
